#!/usr/bin/env bash

set -e

ghc \
    src/Tuple.hs src/Math.hs src/Model.hs src/IO.hs src/Main.hs \
    -o bin/Main
python scripts/data.py $1
cat data/input.csv | bin/Main > data/output.csv
python scripts/plot.py
open pngs/plot.png
