#!/usr/bin/env bash

set -e

view () {
    if [ $(uname -s) = "Darwin" ]; then
        open $1
    else
        xdg-open $1
    fi
}

ghc \
    src/Tuple.hs src/Math.hs src/Model.hs src/IO.hs src/Main.hs \
    -o bin/Main
python scripts/data.py $1
tail -n +2 data/input.csv | bin/Main > data/output.csv
python scripts/plot.py
view pngs/plot.png
