#!/usr/bin/env bash

set -e

if [[ $1 = "lint" ]]; then
    find . -name "*.hs" -exec bash -c 'lint "$0"' {} \;
fi
ghc \
    -O \
    src/Tuple.hs src/Math.hs src/Model.hs src/test/Test.hs \
    -o bin/Test
bin/Test
